version: '3,3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment: 
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      # So you dont have to use root, but you can if you like
      MYSQL_USER: ${MYSQL_USER_DATABASE}
      # You can user password you want
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD}
      # Password for root access
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      # <Port exposed> : < MySQL port running inside container>
      - ${DB_PORT}:3306
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - back_end
    env_file:
      - .env
# Names our volumes
volumes:
  my-db:
networks:
  back_end:
    external: true
    driver: bridge
